{
 "title": "Kafka Connect",
 "tags": [
  "Strimzi",
  "Kafka",
  "Kafka Connect"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Connectors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_count)"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_task_count)"
    }
   ]
  },
  {
   "title": "(Sink/Consumers) Incoming bytes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_incoming_byte_total[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "(Source/Producers) Outgoing bytes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_outgoing_byte_total[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percent", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "graph",
   "description": "JVM Thread Count",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Connector task state with issues",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count) by (connector) != 0",
     "legendFormat": "[paused] {{connector}}"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count) by (connector) != 0",
     "legendFormat": "[failed] {{connector}}"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count) by (connector) != 0",
     "legendFormat": "[unassigned] {{connector}}"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count) by (connector) != 0",
     "legendFormat": "[destroyed] {{connector}}"
    }
   ]
  },
  {
   "title": "Connector task state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Number of connector tasks" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count)",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count)",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count)",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count)",
     "legendFormat": "unassigned"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count)",
     "legendFormat": "destroyed"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_connection_count)",
     "legendFormat": "#consumer connections"
    },
    {
     "expr": "sum(kafka_producer_connection_count)",
     "legendFormat": "#producer connections"
    }
   ]
  }
 ]
}