{
 "title": "Monolith Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Order Create Timer Rate per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_monolith_order_create_timer_rate_per_second",
     "legendFormat": "open"
    }
   ]
  },
  {
   "title": "# order created",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_monolith_order_create_request_total"
    }
   ]
  },
  {
   "title": "# order success",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_monolith_order_create_success_total"
    }
   ]
  },
  {
   "title": "Order Create Timer seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_monolith_order_create_timer_seconds",
     "legendFormat": "{{quantile}} Quantile"
    }
   ]
  },
  {
   "title": "# order created",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_monolith_order_create_request_total",
     "legendFormat": "# orders created"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "System Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "base_cpu_systemLoadAverage", "legendFormat": "open" }
   ]
  }
 ]
}