{
 "title": "Rest Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stock Circuit Breaker Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_ft_ch_puzzle_monolith_stock_control_ArticleStockService_orderArticle_circuitbreaker_open_total",
     "legendFormat": "open"
    },
    {
     "expr": "application_ft_ch_puzzle_monolith_stock_control_ArticleStockService_orderArticle_circuitbreaker_closed_total",
     "legendFormat": "closed"
    },
    {
     "expr": "application_ft_ch_puzzle_monolith_stock_control_ArticleStockService_orderArticle_circuitbreaker_halfOpen_total",
     "legendFormat": "half-open"
    }
   ]
  },
  {
   "title": "Circuit Breaker Invocations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_ft_ch_puzzle_monolith_stock_control_ArticleStockService_orderArticle_invocations_total",
     "legendFormat": "invocations total"
    },
    {
     "expr": "application_ft_ch_puzzle_monolith_stock_control_ArticleStockService_orderArticle_circuitbreaker_callsFailed_total",
     "legendFormat": "failed"
    },
    {
     "expr": "application_ft_ch_puzzle_monolith_stock_control_ArticleStockService_orderArticle_circuitbreaker_callsPrevented_total",
     "legendFormat": "prevented"
    },
    {
     "expr": "application_ft_ch_puzzle_monolith_stock_control_ArticleStockService_orderArticle_circuitbreaker_callsSucceeded_total",
     "legendFormat": "succeeded"
    }
   ]
  },
  { "title": "Order Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "# order created",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_monolith_order_create_request_total"
    }
   ]
  },
  {
   "title": "# order success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_monolith_order_create_success_total"
    }
   ]
  },
  {
   "title": "# stock created",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_monolith_stock_create_total"
    }
   ]
  },
  {
   "title": "# stock updates",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_monolith_stock_update_total"
    }
   ]
  },
  { "title": "Fault Tolerance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}