# curl --request GET
#  --url http://127.0.0.1:8080/shop-orders
GET http://127.0.0.1:8080/shop-orders

###

# curl --request GET
#  --url http://127.0.0.1:8080/article-stocks
GET http://127.0.0.1:8080/article-stocks

###

# curl --request POST
#  --url http://127.0.0.1:8080/shop-orders
#  --header 'Content-Type: application/json'
#  --data '{
#	"articleOrders" : [
#		{
#			"articleId" : 1,
#			"amount" : 1
#		}
#	]
#}'
POST http://127.0.0.1:8080/shop-orders
Content-Type: application/json

{
  "articleOrders": [
    {
      "articleId": 1,
      "amount": 1
    }
  ]
}

###

# curl --request GET
#  --url http://127.0.0.1:8080/chaos-monkey
GET http://127.0.0.1:8080/chaos-monkey

###


# curl --request POST
#  --url http://127.0.0.1:8080/chaos-monkey
#  --header 'Content-Type: application/json'
#  --data '[
#	{
#    "clazzName": "ArticleStockService",
#    "methodName": "orderArticles",
#    "enabled": true,
#    "errorRate": 0.0,
#    "latencyMs": 0,
#    "permitsPerSec": 9.223372036854776E18,
#    "rateLimiterType": "BLOCK",
#    "throwException": true
#  }
#]'
POST http://127.0.0.1:8080/chaos-monkey
Content-Type: application/json

[
  {
    "clazzName": "ArticleStockService",
    "methodName": "orderArticles",
    "enabled": true,
    "errorRate": 0.0,
    "latencyMs": 0,
    "permitsPerSec": 9.223372036854776E18,
    "rateLimiterType": "BLOCK",
    "throwException": true
  }
]

###



###

# curl --request DELETE
#  --url http://127.0.0.1:8080/chaos-monkey/ArticleStockService%23orderArticles
#  --header 'Content-Type: application/json'
DELETE http://127.0.0.1:8080/chaos-monkey/ArticleStockService%23orderArticles
Content-Type: application/json

###

